### ISSUE TITLE
Add more description and rationale to readme

### ISSUE THREAD

**Issue by uvtc** [weavejester/eftest#15]
I was confused about what this is. I think it would be very helpful if you added a sentence near the top of the readme explaining that this is intended for running your tests from the REPL, as opposed to running `lein test` from the shell, presumably for the purpose of avoiding lein start-up time.

Btw, this looks great. Looking forward to trying it out. Thanks!

**Comment by codeasone** [comment]
On my first reading I think it was clear that `eftest` is both a potential `lein-test` runner and a library to aid REPL-based testing with `(run-tests (find-tests "test"))`.

Going to try adopting this too.

**Comment by weavejester** [comment]
If anyone has any concrete suggestions for improving the README I can work them in, but as this issue is pretty vague I'm closing it as I don't know how I can explain Eftest more clearly than it already is.
