### ISSUE TITLE
running meta test using eftest programmatically

### ISSUE THREAD

**Issue by rhacker** [weavejester/eftest#19]
Is there any easy way to run eftest programmatically? Just like `lein eftest :integration` but in code instead. 
Thanks

**Comment by weavejester** [comment]
Yes, it's documented in the README, and is what Eftest was designed to do. To run all tests:

```clojure
(run-tests (find-tests "test"))
```

To run tests that have certain metadata:

```clojure
(run-tests (filter (comp :integration meta) (find-tests "test")))
```

The `find-tests` function returns a collection of vars, so you can filter them based on whatever criteria you desire.

**Comment by rhacker** [comment]
how come I didn't find this in the first place. Thanks!
