### ISSUE TITLE
Is it possible to use eftest with a code coverage tool?

### ISSUE THREAD

**Issue by aviflax** [weavejester/eftest#20]
Such as [Cloverage](https://github.com/cloverage/cloverage)?

I’m coming back to active Clojure use after a break of a few years, so I apologize if this is an obvious or silly question.

Thank you for the excellent tool!

**Comment by weavejester** [comment]
That's more a question for Cloverage I think. I've got no idea if it supports alternative test runners.

**Comment by aviflax** [comment]
OK, thank you!
