### ISSUE TITLE
Indenting is wrong for multi-line failure results

### ISSUE THREAD

**Issue by danielcompton** [weavejester/eftest#22]
If eftest's expected/actual output spans multiple lines then the extra lines aren't indented enough. They need to have the additional indentation provided by `expected: ` prefixed before they are printed.

```console
$ lein eftest

FAIL in eftest-test.core-test/my-test (core_test.clj:10)
expected: {:a 1,
 :aaaaaaaaa 12512521,
 :b "abdksdaflsdfjsdkfla",
 :bbbbbbbb 1251251212512512,
 :ccccccccc ""}
  actual: {:a 2, :b "abdksdfksdflaksdfal"}

FAIL in eftest-test.core-test/a-test (core_test.clj:7)
FIXME, I fail.
expected: 0
  actual: 1

2/2   100% [==================================================]  ETA: 00:00

Ran 2 tests in 0.035 seconds
2 assertions, 2 failures, 0 errors.
Tests failed.
```

I think humane-test-output [does this](https://github.com/pjstadig/humane-test-output/blob/0.8.3/src/pjstadig/util.cljc#L9) using `pp/pprint-logical-block` to add the prefixes.

**Comment by danielcompton** [comment]
Would you be able to cut a new release sometime @weavejester? There's a bunch of cool stuff that has been added.

**Comment by weavejester** [comment]
Working on it. There was at least one issue that slipped through the code review of a PR.

**Comment by weavejester** [comment]
Make that two things...
