### ISSUE TITLE
Return test results rather than nil

### ISSUE THREAD

**Issue by jcf** [weavejester/eftest#3]
Hi James,

I'm interested in using eftest during CI, which would mean I need to know if tests have failed. With that information I can exit with a non-zero status etc.

Would you be open to returning a map that describes the test run rather than `nil` in order to make this possible?

**Comment by weavejester** [comment]
Yep, that sounds like a good idea 👍

**Comment by jcf** [comment]
I should have some time to put something together later this week. Thanks, James!
