### ISSUE TITLE
Support for running a single test from command line

### ISSUE THREAD

**Issue by psyho** [weavejester/eftest#37]
With `lein test` I can run a single test with a command like `lein test :only foo.bar/baz`. As far as I can tell, `lein eftest` only supports running tests for entire namespaces. Is there support for running a single test and if so, how can I do it?

PS. Thanks for this excellent library, I think this is the most complete clojure test runner that I encountered so far!

**Comment by johanatan** [comment]
:+1:

**Comment by johanatan** [comment]
I came here to open the same issue and found this existing one instead. :)

**Comment by weavejester** [comment]
Eftest copies a bunch of code from `lein test`, but this may be functionality that is not in the Eftest Leiningen plugin yet.

**Comment by jayemar** [comment]
For those coming here to find the syntax, if you want to run the tests for a single namespace you don't need the `:only` keyword, but you do if you want to run a single test from a single namespace:
```sh
# Run all tests in my-namespace
lein eftest my-project.my-namespace
lein eftest :only my-project.my-namespace

# Run a single test in my-namespace
lein eftest :only my-project.my-namespace/test-to-run
```
