### ISSUE TITLE
Wrong failure reporting

### ISSUE THREAD

**Issue by manuel-uberti** [weavejester/eftest#42]
First of all, thanks for this great tool.

With `lein-eftest` 0.4.3 I get this, which is what I am expecting:
```
$ lein eftest

54/54   100% [==================================================]  ETA: 00:00

Ran 54 tests in 0.184 seconds
55 assertions, 0 failures, 0 errors.
```
However, with `lein-eftest` 0.5.0 I get this:
```
$ lein eftest

30/54    55% [===========================                       ]  ETA: 00:00FAIL in boodle.api.resources.saving-test/insert-test (saving_test.clj:27)
30/54    55% [===========================                       ]  ETA: 00:00Testing insert saving resource
51/54    94% [===============================================   ]  ETA: 00:00expected: {:amount "3,5", :item "test"}
  actual: {:amount 3.5, :item "test"}
    diff: - {:amount "3,5"}
          + {:amount 3.5}

54/54   100% [==================================================]  ETA: 00:00

Ran 54 tests in 0.230 seconds
55 assertions, 1 failure, 0 errors.
Tests failed.
```
The code I am testing is here, if you want more details: https://github.com/manuel-uberti/boodle/blob/master/test/clj/boodle/api/resources/saving_test.clj

**Comment by weavejester** [comment]
It looks like this is two problems.

The report function isn't being synchronized across namespaces, leading to a weird output when it reports a failure. I'll go ahead and fix this.

The failure itself looks like it's caused because your tests are not thread safe, and Eftest runs multithreaded by default. I'm considering changing that so that it runs single-threaded by default.

**Comment by manuel-uberti** [comment]
I see, thank you.

For the second problem, it should be enough to add `:multithread? false` to `:eftest` in my project.clj, shouldn't it?

But I have to fix my tests, of course. :)

**Comment by weavejester** [comment]
Right. `:multithread? false` should work.

**Comment by manuel-uberti** [comment]
Yes, just tried and it's working now. I guess we can close this one now. Thank you again.
