### ISSUE TITLE
JDK 11 support

### ISSUE THREAD

**Issue by tirkarthi** [weavejester/eftest#53]
eftest fails on JDK 11 since it uses fipp which in turn uses core.rrb-vector which has JDK 11 related compilation errors. This has been fixed in core.rrb-vector master branch and there is an upstream issue in fipp to make sure it's updated. I am opening this here as a reminder issue so that eftest can be updated. Currently this blocks JDK 11 testing in boot since it depends on eftest.

Upstream issue : https://github.com/brandonbloom/fipp/issues/50
eftest JDK 11 failure : https://travis-ci.org/tirkarthi/eftest/jobs/402075270
core.rrb-vector issue : https://dev.clojure.org/jira/browse/CRRBV-18

Thanks

**Comment by weavejester** [comment]
Thanks for the information. When core.rrb-vector is updated, I'll cut a new release of Eftest.

**Comment by jcf** [comment]
From [CRRBV-18](https://dev.clojure.org/jira/browse/CRRBV-18?focusedCommentId=50948&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-50948):

> This was merged in https://github.com/clojure/core.rrb-vector/commit/b489b3249d56bb6a104c2d4ead2da8ade8dd29b4 and is available in version 0.0.12 and later (0.0.13 is the latest version at the time of writing). For easy copy/pasting:

```
[org.clojure/core.rrb-vector "0.0.13"]
```

**Comment by tirkarthi** [comment]
Thanks @jcf for the details. I am closing this.
