### ISSUE TITLE
Slow test names incorrect

### ISSUE THREAD

**Issue by royaldark** [weavejester/eftest#56]
This is a regression somewhere between 0.5.0 and 0.5.2.

Under 0.5.2, but not 0.5.0, the names of slow tests have begun referring to fixtures instead of the actual test var.

Before (0.5.0):
```
LONG TEST in org.kidblog.rollouts.test-rollout/test-generated-rollouts
Test took 7.267 seconds seconds to run
```

Now (0.5.2):
```
LONG TEST in org.kidblog.rollouts.test-rollout during :clojure.test/once-fixtures
Test took 5.051 seconds seconds to run
```

**Comment by weavejester** [comment]
Thanks for the report. Looks like the regression was caused by 916b5937c346e45206197454f4d38a62ee373cd9.

**Comment by robertfw** [comment]
Are there any workarounds for this, or perhaps guidelines for a fix? Ran into this just now when I sat down to try and optimize our test suite

**Comment by weavejester** [comment]
No workarounds are known. Someone just needs to write a PR to fix it.
