### ISSUE TITLE
lein eftest doesn't seem to run my clean up function

### ISSUE THREAD

**Issue by ndchorley** [weavejester/eftest#86]
In my tests as part of [this project](https://github.com/ndchorley/chess), I create a directory (`events-directory`) and then some directories inside it. At the beginning of each test, I have a clean up function, `there-are-no-events` that just deletes anything inside `events-directory`.

Curiously, when I run `lein eftest`, one of the tests, `the-events-page-lists-events-by-date-descending`, is failing because it finds more data there than there should be. This suggests that the clean up function isn't being run for some reason. If, however, I run `lein test`, everything is as expected and the clean up happens.

What am I missing here?

**Comment by weavejester** [comment]
You'll want to set your tests to run in serial. See the [multithreading](https://github.com/weavejester/eftest#multithreading) section of the README.

**Comment by ndchorley** [comment]
Thanks for the quick response!
