### ISSUE TITLE
NPE in test

### ISSUE THREAD

**Issue by behrica** [weavejester/eftest#89]
I am getting this:

```clojure
                                                                              ERROR in  (Numbers.java:1095)
expected: (< avg-mae max-avg-loss)
  actual: 
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "x" is null
                                             ...                         
                          progrock.core/bar-text           core.clj:   33
                            progrock.core/render           core.clj:   91
                             progrock.core/print           core.clj:  104
           eftest.report.progress/print-progress       progress.clj:   18
              eftest.report.progress/eval2715/fn       progress.clj:   42
                                             ...                         
                          clojure.test/do-report           test.clj:  357
```

Using an other test runner, all tests apss

**Comment by behrica** [comment]
I noticed that I have some arbitrary vars in my test name space.
So non-tests and non-functions and non defs.

Not sure, this is a bug.
Other runners / reportes dont care apparentely
The vars are "valid" Clojure syntax and execute fine.

**Comment by weavejester** [comment]
Strange. Are you running eftest in its default multithreaded mode? Is there a project or way I could reproduce this error?

**Comment by behrica** [comment]
Let's close it.
I had it while I had some "left over" code snippets in my namespace.
Cannot reproduce anymore.

If it comes back, we can reopen.
