### ISSUE TITLE
Catch output for successful tests

### ISSUE THREAD

**Issue by miikka** [weavejester/eftest#9]
Some test runners – like [pytest](https://docs.pytest.org/en/latest/) – show whatever a test would print to stdout only when the test fails. This is helpful when dealing with large, noisy test suites. For example, I encountered a test suite that printed hundreds of lines of stack traces *even when every tests passed*. It's hard to find the failing test out of that noise.

I'd like to have this feature in Eftest as well and I'd be happy to implement it. What do you think?

One hurdle is that programs can print stuff in a bunch of ways and there's no fool-proof way to catch them all. My suggestion is to just catch whatever goes to `*out*`, and maybe investigate what can be done with `System/setOut`. I think this should cover a lot of cases already.

**Comment by weavejester** [comment]
I think this is a good idea, and I agree that `*out*` plus `System/setOut` should be sufficient to catch most cases.

**Comment by NoamB** [comment]
+1

**Comment by Deraen** [comment]
Implemented in https://github.com/weavejester/eftest/pull/24
